name: "ğŸ‘·â€â™‚ï¸ Dispatch slash commands"

on:
  issue_comment:
    types:
      - created

permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch ğŸš€
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          permission: write
          commands: |
            create-rc
            help
